### ISSUE TITLE
Bedre DIKUmemes

### ISSUE THREAD

**Issue by Eckankar** [kantinen/kantinfo#17]
Lige nu kører jeg en DIKUmemes ting på min server: https://gist.github.com/Eckankar/e882c1235a49f44c7af0

Det fungerer fint nok, på nær, at den token vi får skal fornys med nogle få måneders mellemrum, og det sker manuelt. Er der nogen der har en bedre idé?

**Comment by athas** [comment]
Sebastian Paaske Tørholm notifications@github.com writes:

> Lige nu kører jeg en DIKUmemes ting på min server: https://gist.github.com/Eckankar/e882c1235a49f44c7af0
> 
> Det fungerer fint nok, på nær, at den token vi får skal fornys med
> nogle få måneders mellemrum, og det sker manuelt. Er der nogen der har
> en bedre idé?

Jeg foreslår at den fornys automatisk.

## 

\  Troels
/\ Henriksen

**Comment by Eckankar** [comment]
2015-08-27 10:54 GMT+02:00 Troels Henriksen notifications@github.com:

> Sebastian Paaske Tørholm notifications@github.com writes:
> 
> > Lige nu kører jeg en DIKUmemes ting på min server:
> > https://gist.github.com/Eckankar/e882c1235a49f44c7af0
> > 
> > Det fungerer fint nok, på nær, at den token vi får skal fornys med
> > nogle få måneders mellemrum, og det sker manuelt. Er der nogen der har
> > en bedre idé?
> 
> Jeg foreslår at den fornys automatisk
> ​.​

​Har du et bud på hvordan dette kan gøres? Jeg kunne ikke umiddelbart finde
en tilfredsstillende måde at gøre det på.

## 

-Sebastian

**Comment by Eckankar** [comment]
Hører til https://github.com/datalogisk-kantineforening/infoscreen. Lukker.
