### ISSUE TITLE
More English in our slides

### ISSUE THREAD

**Issue by nqpz** [kantinen/kantinfo#23]
We have several international students, and they do occasionally appear in the canteen.  To accomodate them, our slides should have more content in English.

As a start, I have modified the IRC slide to have login instructions in both Danish and Engilsh, chosen at random whenever the silde is shown.  More slides can follow this approach.

**Comment by Eckankar** [comment]
This should be moved to the infoscreen repo.

**Comment by nqpz** [comment]
Yes.
