### ISSUE TITLE
Support for delvis afspilning af videoer

### ISSUE THREAD

**Issue by truls** [kantinen/kantinfo#29]
Det bør være muligt kun at vise dele af en video så det fx. bliver muligt at tilføje dele af lange youtube videoer.

Det er oplagt at specificere det i yaml filen via parametre i stil med:

startat: 01:40
stopat: 03:50

**Comment by MikkelStorgaard** [comment]
Det er nu gjort med start_pos , end_pos

**Comment by MikkelStorgaard** [comment]
og intervals
