### ISSUE TITLE
Make it possible to have content shown only in certain intervals

### ISSUE THREAD

**Issue by dybber** [kantinen/kantinfo#3]
Examples:
- every day from 15:00 to 5:00 in the morning
- every friday

**Comment by athas** [comment]
I recommend designing this not by embedding information in the file name
(as I previously discussed with Niels), but by having a metadata file
alongside the main file.  This file could also contain duration and
the like.

## 

\  Troels
/\ Henriksen

**Comment by nqpz** [comment]
On 2015-03-27 08:07:55, Troels Henriksen wrote:

> I recommend designing this not by embedding information in the file name
> (as I previously discussed with Niels), but by having a metadata file
> alongside the main file.  This file could also contain duration and
> the like.

Then let's use YAML.  There's an okay Python library for that (which is
even installed on the odroid!).

I might implement this today.

**Comment by oleks** [comment]
On Fri, Mar 27, 2015 at 7:02 PM, Niels G. W. Serup <notifications@github.com

**Comment by nqpz** [comment]
On 2015-03-27 14:30:53, Oleksandr Shturmov wrote:

> On Fri, Mar 27, 2015 at 7:02 PM, Niels G. W. Serup notifications@github.com wrote:
> 
> > On 2015-03-27 08:07:55, Troels Henriksen wrote:
> > 
> > > I recommend designing this not by embedding information in the file name
> > > (as I previously discussed with Niels), but by having a metadata file
> > > alongside the main file. This file could also contain duration and
> > > the like.
> > 
> > Then let's use YAML. There's an okay Python library for that (which is
> > even installed on the odroid!).
> > 
> > I might implement this today.
> 
> YAML: Y A Markup Language. Tro-lo-lo-lo.

Y A?

**Comment by oleks** [comment]
On Fri, Mar 27, 2015 at 10:34 PM, Niels G. W. Serup <
notifications@github.com> wrote:

> On 2015-03-27 14:30:53, Oleksandr Shturmov wrote:
> 
> > On Fri, Mar 27, 2015 at 7:02 PM, Niels G. W. Serup <
> > notifications@github.com> wrote:
> > 
> > > On 2015-03-27 08:07:55, Troels Henriksen wrote:
> > > 
> > > > I recommend designing this not by embedding information in the file
> > > > name
> > > > (as I previously discussed with Niels), but by having a metadata file
> > > > alongside the main file. This file could also contain duration and
> > > > the like.
> > > 
> > > Then let's use YAML. There's an okay Python library for that (which is
> > > even installed on the odroid!).
> > > 
> > > I might implement this today.
> > 
> > YAML: Y A Markup Language. Tro-lo-lo-lo.
> 
> Y A?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datalogisk-kantineforening/infoscreen/issues/3#issuecomment-87097898
> .

also known as "whY A Markup Language", but I fear that you are trolling me
now.

**Comment by nqpz** [comment]
On 2015-03-27 14:43:40, Oleksandr Shturmov wrote:

> On Fri, Mar 27, 2015 at 10:34 PM, Niels G. W. Serup notifications@github.com wrote:
> 
> > On 2015-03-27 14:30:53, Oleksandr Shturmov wrote:
> > 
> > > On Fri, Mar 27, 2015 at 7:02 PM, Niels G. W. Serup notifications@github.com wrote:
> > > 
> > > > On 2015-03-27 08:07:55, Troels Henriksen wrote:
> > > > 
> > > > > I recommend designing this not by embedding information in the file name
> > > > > (as I previously discussed with Niels), but by having a metadata file
> > > > > alongside the main file. This file could also contain duration and
> > > > > the like.
> > > > 
> > > > Then let's use YAML. There's an okay Python library for that (which is
> > > > even installed on the odroid!).
> > > > 
> > > > I might implement this today.
> > > 
> > > YAML: Y A Markup Language. Tro-lo-lo-lo.
> > 
> > Y A?
> 
> also known as "whY A Markup Language", but I fear that you are trolling me
> now.

The only one trolling is you, especially by continually including the
footers!

**Comment by nqpz** [comment]
We support a 'duration' configuration in .yaml files now, but we don't support anything more advanced.
