### ISSUE TITLE
SD-kortet er ved at rådne op

### ISSUE THREAD

**Issue by athas** [kantinen/kantinfo#7]
Det holdt ikke længere end et par uger.  Langt det meste af tiden er filsystemet skrivebeskyttet grundet utallige IO-fejl.  HVad gør vi?

**Comment by Eckankar** [comment]
@br0ns sagde noget om, at det muligvis ikke var SD-kortet, men en eller anden on-board memory chip man kunne fjerne?

**Comment by athas** [comment]
...også hvis SD-kortet er i stykker?

## 

\  Troels
/\ Henriksen

**Comment by nqpz** [comment]
On 2015-04-14 05:23:24, Troels Henriksen wrote:

> ...også hvis SD-kortet er i stykker?

Måske er det en kombination!

**Comment by kristoff3r** [comment]
On Tue, Apr 14, 2015 at 2:33 PM, Niels G. W. Serup <notifications@github.com

> wrote:
> 
> On 2015-04-14 05:23:24, Troels Henriksen wrote:
> 
> > ...også hvis SD-kortet er i stykker?
> 
> Måske er det en kombination!

Den siger at fejlen er i mmcblk0, som er et MMC kort og ikke SD-kortet. Er
der andre indikationer på at det er SD-kortet den (også) fejler?

**Comment by athas** [comment]
Tag et kig i `/lost+found`.

**Comment by nqpz** [comment]
Truls har dd'et på ny, og nu kører det, men der er vist stadig lidt fejl på det.  Vi ser lige på det igen efter eksamenerne.

Men det kører reelt nu.

**Comment by truls** [comment]
On 14/04/15 05:49, Kristoffer Søholm wrote:

> On Tue, Apr 14, 2015 at 2:33 PM, Niels G. W. Serup <notifications@github.com
> 
> > wrote:
> > 
> > On 2015-04-14 05:23:24, Troels Henriksen wrote:
> > 
> > > ...også hvis SD-kortet er i stykker?
> > 
> > Måske er det en kombination!
> 
> Den siger at fejlen er i mmcblk0, som er et MMC kort og ikke SD-kortet. Er
> der andre indikationer på at det er SD-kortet den (også) fejler?

mmcblk driveren styrer også SD-kort. Der er ikke andre
storage-enheder tilknyttet den end SD-kortet og kortet giver også I/O-fejl
i min datamat. Dog kører infoskærmen igen efter at samme kort fik dd'et
nyt image.

**Comment by athas** [comment]
Hil Truls, infoskærmsprofeten!

Sandelig er dette uden tvivl en varig og permanent løsning.
