### ISSUE TITLE
Lav netværksboot til odroiden

### ISSUE THREAD

**Issue by truls** [kantinen/kantinfo#8]
Forhåbentlig vis vil det være hurtigere og mere stabilt at netværksboote odroiden fra kantineserveren end at køre det hele fra SD-kortet.

Gør det efter eksamen...

**Comment by athas** [comment]
Ja!  Det vil nok være en god idé.  Jeg synes dog stadigvæk vi skal
dokumentere uafhængig opsætning, hvis kantineserveren nu dør engang i
fremtiden.

## 

\  Troels
/\ Henriksen

**Comment by truls** [comment]
Den bedste "dokumentation" er nok bare at lavet et script som kan lave infoskærms-opsætningen ud fra et standard odroid image

**Comment by athas** [comment]
truls notifications@github.com writes:

> Den bedste "dokumentation" er nok bare at lavet et script som kan lave
> infoskærms-opsætningen ud fra et standard odroid image

Enig.

## 

\  Troels
/\ Henriksen

**Comment by nqpz** [comment]
Jeg har just skubbet `setup.sh`, men det er ikke færdigt.  Nogen andre må godt lige kigge på dets kommentarer og kode resten.

**Comment by truls** [comment]
Guide til odroid netboot http://forum.odroid.com/viewtopic.php?f=52&t=7116

**Comment by truls** [comment]
Hmm, jeg skal åbenbart lige have oversat en toolchain som kan generere ARM-binaries før jeg kan bygge en kerne med NFS-support, så det er muligt at projektet trækker lidt ud

**Comment by athas** [comment]
truls notifications@github.com writes:

> Hmm, jeg skal åbenbart lige have oversat en toolchain som kan generere
> ARM-binaries før jeg kan bygge en kerne med NFS-support, så det er
> muligt at projektet trækker lidt ud

Oversæt på odroiden!

Med det nye SD-kort du naturligvis har købt!

## 

\  Troels
/\ Henriksen

**Comment by athas** [comment]
Synes vi stadigvæk at det her er en god idé?

**Comment by truls** [comment]
Umidelbart ja? Dog har det nuværende SD-kort holdt relativt længe så incitamentet er blevet mindre.

**Comment by athas** [comment]
Jeg er selv kommet frem til at hvis SD-kortet dør, men hele vores setup er bygget op omkring lokal boot, så er det ret nemt for enhver med basal Unix-kendskab at genskabe.  Hvis vi bruger netværksboot, og serveren engang dør, så er det sværere for en gennemsnitlig kantinebruger at gendanne.  For mig er det bedre at have hyppige nedbrud vi kan løse, end sjældne nedbrud vi måske ikke kan.

**Comment by nqpz** [comment]
Urelateret til kernesystemet.
